# Generated by Django 5.0.6 on 2024-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
